DROP TABLE IF EXISTS tab_account;
create table tab_account(id integer auto_increment primary key not null, role_id integer unique not null , account varchar(255) unique not null , role_name varchar(255) not null , last_login_time integer not null default 0 ) engine=innodb CHARSET=utf8;
DROP TABLE IF EXISTS tab_achievement;
create table tab_achievement(id integer auto_increment primary key not null, role_id integer  not null , achieve_id integer  not null , achieve_level integer not null , data varchar(255) not null default '[]' , index (role_id), index (achieve_id)) engine=innodb CHARSET=utf8;
DROP TABLE IF EXISTS tab_dragon;
create table tab_dragon(id integer auto_increment primary key not null, role_id integer unique not null , dragon_id integer not null , level integer not null default 0 , exp integer not null default 0 , magic integer not null default 0 , rage integer not null default 0 ) engine=innodb CHARSET=utf8;
DROP TABLE IF EXISTS tab_item;
create table tab_item(id integer auto_increment primary key not null, role_id integer  not null , item_id integer  not null default 0 , type_id integer not null default 0 , location integer not null default 0 , embe_items varchar(255) not null default '[]' , amount integer not null default 0 , start_time integer not null default 0 , end_time integer not null default 0 , morale integer not null default 0 , used_times integer not null default 0 , attr varchar(1024) not null default '[]' , is_bind boolean not null default true , firm_exp integer not null default 0 , firm_lv integer not null default 0 , endurance integer not null default 0 , colour integer not null default 1 , index (role_id), index (item_id)) engine=innodb CHARSET=utf8;
DROP TABLE IF EXISTS tab_magic_book;
create table tab_magic_book(id integer auto_increment primary key not null, role_id integer  not null , magic_id integer  not null default 0 , book_id integer not null default 0 , magic_level integer not null default 0 , has_learned boolean default false , index (role_id), index (magic_id)) engine=innodb CHARSET=utf8;
DROP TABLE IF EXISTS tab_magic_data;
create table tab_magic_data(id integer auto_increment primary key not null, role_id integer unique not null , max_scroll integer not null default 10 , magic_crystal integer not null default 0 ) engine=innodb CHARSET=utf8;
DROP TABLE IF EXISTS tab_role_chat;
create table tab_role_chat(id integer auto_increment primary key not null, role_id integer unique not null , no_speak integer not null default 0 ) engine=innodb CHARSET=utf8;
DROP TABLE IF EXISTS tab_role_pos;
create table tab_role_pos(id integer auto_increment primary key not null, role_id integer unique not null , cur_mapid integer not null , cur_x integer not null , cur_y integer not null , dir integer not null default 0 ) engine=innodb CHARSET=utf8;
DROP TABLE IF EXISTS tab_role_data;
create table tab_role_data(id integer auto_increment primary key not null, role_id integer unique not null , role_level integer not null default 1 , role_exp integer not null default 0 , reserve_troops integer not null default 2 , bag_capacity integer not null default 50 ) engine=innodb CHARSET=utf8;
DROP TABLE IF EXISTS tab_troops;
create table tab_troops(id integer auto_increment primary key not null, role_id integer  not null , troops_id integer not null default 0 , troops_amount integer not null default 0 , place integer  not null default 0 , level integer not null default 1 , exp integer not null default 0 , index (role_id), index (place)) engine=innodb CHARSET=utf8;
DROP TABLE IF EXISTS tab_fight_attr;
create table tab_fight_attr(id integer auto_increment primary key not null, role_id integer unique not null , hero_id integer not null , leadership integer not null default 0 , attack integer not null default 0 , defence integer not null default 0 , intel integer not null default 0 , magic integer not null default 0 , max_magic integer not null default 0 , rage integer not null default 0 , max_rage integer not null default 0 , move_speed integer not null default 0 ) engine=innodb CHARSET=utf8;
DROP TABLE IF EXISTS tab_rune;
create table tab_rune(id integer auto_increment primary key not null, role_id integer unique not null , str_rune integer not null default 0 , will_rune integer not null default 0 , magic_rune integer not null default 0 , str_rune_skills varchar(255) not null default '[]' , will_rune_skills varchar(255) not null default '[]' , magic_rune_skills varchar(255) not null default '[]' ) engine=innodb CHARSET=utf8;
DROP TABLE IF EXISTS tab_log_item;
create table tab_log_item(id integer auto_increment primary key not null, role_id integer unique not null , item_typeid integer not null default 0 , item_name varchar(255) not null default '' , log_descript varchar(255) not null default '' ) engine=innodb CHARSET=utf8;
DROP TABLE IF EXISTS tab_log_gold;
create table tab_log_gold(id integer auto_increment primary key not null, role_id integer unique not null , old_gold integer not null default 0 , new_gold integer not null default 0 , in_or_use integer not null default 1 , log_descript varchar(255) not null default '' ) engine=innodb CHARSET=utf8;
